{"name": "test_login_invalid_account", "status": "passed", "attachments": [{"name": "login error message", "source": "24d7a6fe-c58b-4e80-8073-b67d2692c158-attachment.png", "type": "image/png"}, {"name": "log", "source": "c0b23114-d1fb-4624-b834-2d46ddb0e50d-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "eb2fa13c-1f2f-4f0a-834d-95ac5277216f-attachment.txt", "type": "text/plain"}], "start": 1723203199847, "stop": 1723203212009, "uuid": "0e771c03-ec6b-4327-8b82-416e9fc3d3ba", "historyId": "a6c4a94889f45ad75b8d28ae6cd39658", "testCaseId": "a6c4a94889f45ad75b8d28ae6cd39658", "fullName": "test.web.test_login_invalid_account.UnsuccessfulLoginTest#test_login_invalid_account", "labels": [{"name": "story", "value": "Login with Invalid Credentials"}, {"name": "feature", "value": "Login Test - invalid password"}, {"name": "parentSuite", "value": "test.web"}, {"name": "suite", "value": "test_login_invalid_account"}, {"name": "subSuite", "value": "UnsuccessfulLoginTest"}, {"name": "host", "value": "DESKTOP-OPJ94K2"}, {"name": "thread", "value": "17628-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test.web.test_login_invalid_account"}]}