{"name": "test_intentional_failure", "status": "failed", "statusDetails": {"message": "AssertionError: True is not false : User should not be logged in, but they are.", "trace": "self = <test_for_jira.FailedTestForJira testMethod=test_intentional_failure>\n\n    @allure.story(\"Intentional Failure for Jira Integration\")\n    def test_intentional_failure(self):\n        \"\"\"\n        This test demonstrates Jira integration for failed tests by intentionally asserting that a successful login\n        should fail. It logs in with valid credentials, verifies the login, then falsely asserts the login failed.\n        The purpose is to confirm that when a test fails, a Jira issue is automatically\n        created, enabling automated tracking of test failures.\n        \"\"\"\n    \n        # Arrange\n        first_page = FirstPage(self.driver)\n        login_page = LoginPage(self.driver)\n    \n        # Act\n        first_page.click_login_button()\n        login_page.fill_login_email_input(self.config['email'])\n        login_page.click_continue_button()\n        login_page.fill_login_password_input(self.config['password'])\n        login_page.click_continue_button()\n    \n        is_logged_in = WebDriverWait(self.driver, 10).until(\n            EC.url_contains(self.config['username'])\n        )\n    \n        # Assert\n        try:\n>           self.assertFalse(is_logged_in, \"User should not be logged in, but they are.\")\nE           AssertionError: True is not false : User should not be logged in, but they are.\n\ntest\\web\\test_for_jira.py:50: AssertionError"}, "description": "\n        This test demonstrates Jira integration for failed tests by intentionally asserting that a successful login\n        should fail. It logs in with valid credentials, verifies the login, then falsely asserts the login failed.\n        The purpose is to confirm that when a test fails, a Jira issue is automatically\n        created, enabling automated tracking of test failures.\n        ", "attachments": [{"name": "test_result_screenshot", "source": "06f82b87-f427-426e-a185-d8f043a8af69-attachment.png", "type": "image/png"}, {"name": "log", "source": "3fa22b9d-39c1-431d-b8e9-f9a5e8d8f6ae-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "ff1a1c66-512a-4e97-8458-e3ab95023b71-attachment.txt", "type": "text/plain"}], "start": 1723327992365, "stop": 1723328005591, "uuid": "025ed154-7f97-46cb-8066-0677bc0cee43", "historyId": "7af040c5d6df1d0dccc826b1aea4a615", "testCaseId": "7af040c5d6df1d0dccc826b1aea4a615", "fullName": "test.web.test_for_jira.FailedTestForJira#test_intentional_failure", "labels": [{"name": "story", "value": "Intentional Failure for Jira Integration"}, {"name": "parentSuite", "value": "test.web"}, {"name": "suite", "value": "test_for_jira"}, {"name": "subSuite", "value": "FailedTestForJira"}, {"name": "host", "value": "DESKTOP-OPJ94K2"}, {"name": "thread", "value": "14936-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test.web.test_for_jira"}]}